#! /bin/sh
#
#  %Z% %M% %E% %I%
#
# Test harness for testing out configure.inc


for x in t.*;do
    printf "$x\t"
    MSG=`sh ./$x`
    if [ "$?" -ne 0 ]; then
	echo "failed ($MSG)"
	exit 1;
    fi
    rm -f config.*
    echo "passed"
done
exit 0
